import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Parses URL links from the anchor tags within HTML text.
 *
 * @author CS 212 Software Development
 * @author University of San Francisco
 * @version Summer 2021
 */
public class LinkParser {
	/**
	 * Removes the fragment component of a URL (if present), and properly encodes
	 * the query string (if necessary).
	 *
	 * @param url the url to normalize
	 * @return normalized url
	 * @throws URISyntaxException if unable to craft new URI
	 * @throws MalformedURLException if unable to craft new URL
	 */
	public static URL normalize(URL url) throws MalformedURLException, URISyntaxException {
		return new URI(url.getProtocol(), url.getUserInfo(), url.getHost(), 
				url.getPort(), url.getPath(), url.getQuery(), null).toURL();
	}

	/**
	 * Returns a list of all the valid HTTP(S) links found in the href attribute
	 * of the anchor tags in the provided HTML. The links will be converted to
	 * absolute using the base URL and normalized (removing fragments and encoding
	 * special characters as necessary).
	 * 
	 * Any links that are unable to be properly parsed (throwing an
	 * {@link MalformedURLException}) or that do not have the HTTP/S protocol will
	 * not be included.
	 *
	 * @param base the base url used to convert relative links to absolute3
	 * @param html the raw html associated with the base url
	 * @return list of all valid http(s) links in the order they were found
	 */
	public static ArrayList<URL> getValidLinks(URL base, String html) {
		ArrayList<URL> validLinks = new ArrayList<>();
		String aTagRegex = "(?is)<a.*?>";
		Matcher matcher = Pattern.compile(aTagRegex).matcher(html);

		while (matcher.find()) {
			String matched = matcher.group();
			String hrefRegex = "(?is)href\\s*?=.*?\".*?\"";
			Matcher innerMatcher = Pattern.compile(hrefRegex).matcher(matched);
			
			while (innerMatcher.find()) {
				try {FileWriter a = new FileWriter("neato.txt");
				String inner = innerMatcher.group();
				a.write("FOUND: " + inner);
				a.flush();
					validLinks.add( normalize( new URL(base, inner
							.replaceAll("[\r\n]", "")
							.replaceAll("(?is)href\s*?=", "")
							.replaceAll("\"", ""))));
					
					a.close();
				}
				catch (Exception e) {
					System.out.println("Oh - LinkParser: " + e);
				}
			}
		}
		
		return validLinks;
	}
	
	/**
	 * Demonstrates this class.
	 * @param args unused
	 * @throws Exception if any issues occur
	 */
	public static void main(String[] args) throws Exception {
		// this demonstrates cleaning
		URL valid = new URL("https://docs.python.org/3/library/functions.html?highlight=string#format");
		System.out.println(" Link: " + valid);
		System.out.println("Clean: " + normalize(valid));
		System.out.println();

		// this demonstrates encoding
		URL space = new URL("https://www.google.com/search?q=hello world");
		System.out.println(" Link: " + space);
		System.out.println("Clean: " + normalize(space));
		System.out.println();

		ArrayList<URL> validLinks = getValidLinks(new URL("https://www.cs.usfca.edu/~cs212/javadoc/api/allclasses-index.html"), "After processing: <!DOCTYPE HTML>\n"
				+ "\n"
				+ "<html lang=\"en\">\n"
				+ "\n"
				+ "<body class=\"class-declaration-page\">\n"
				+ "\n"
				+ "\n"
				+ "<div class=\"flex-box\">\n"
				+ "<header role=\"banner\" class=\"flex-header\">\n"
				+ "<nav role=\"navigation\">\n"
				+ "\n"
				+ "<div class=\"top-nav\" id=\"navbar.top\">\n"
				+ "<div class=\"skip-nav\"><a href=\"#skip.navbar.top\" title=\"Skip navigation links\">Skip navigation links</a></div>\n"
				+ "<ul id=\"navbar.top.firstrow\" class=\"nav-list\" title=\"Navigation\">\n"
				+ "<li><a href=\"../../../../../index.html\">Overview</a></li>\n"
				+ "<li><a href=\"../../../../module-summary.html\">Module</a></li>\n"
				+ "<li><a href=\"package-summary.html\">Package</a></li>\n"
				+ "<li class=\"nav-bar-cell1-rev\">Class</li>\n"
				+ "<li><a href=\"class-use/AbstractElementVisitor6.html\">Use</a></li>\n"
				+ "<li><a href=\"package-tree.html\">Tree</a></li>\n"
				+ "<li><a href=\"../../../../../deprecated-list.html\">Deprecated</a></li>\n"
				+ "<li><a href=\"../../../../../index-files/index-1.html\">Index</a></li>\n"
				+ "<li><a href=\"../../../../../help-doc.html\">Help</a></li>\n"
				+ "</ul>\n"
				+ "<div class=\"about-language\"><div style=\"margin-top: 14px;\"><strong>Java SE 15 &amp; JDK 15</strong> </div></div>\n"
				+ "</div>\n"
				+ "<div class=\"sub-nav\">\n"
				+ "<div>\n"
				+ "<ul class=\"sub-nav-list\">\n"
				+ "<li>Summary:&nbsp;</li>\n"
				+ "<li>Nested&nbsp;|&nbsp;</li>\n"
				+ "<li>Field&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#constructor.summary\">Constr</a>&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#method.summary\">Method</a></li>\n"
				+ "</ul>\n"
				+ "<ul class=\"sub-nav-list\">\n"
				+ "<li>Detail:&nbsp;</li>\n"
				+ "<li>Field&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#constructor.detail\">Constr</a>&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#method.detail\">Method</a></li>\n"
				+ "</ul>\n"
				+ "</div>\n"
				+ "<div class=\"nav-list-search\"><label for=\"search\">SEARCH:</label>\n"
				+ "<input type=\"text\" id=\"search\" value=\"search\" disabled=\"disabled\">\n"
				+ "<input type=\"reset\" id=\"reset\" value=\"reset\" disabled=\"disabled\">\n"
				+ "</div>\n"
				+ "</div>\n"
				+ "\n"
				+ "<span class=\"skip-nav\" id=\"skip.navbar.top\">\n"
				+ "\n"
				+ "</span></nav>\n"
				+ "</header>\n"
				+ "<div class=\"flex-content\">\n"
				+ "<main role=\"main\">\n"
				+ "\n"
				+ "<div class=\"header\">\n"
				+ "<div class=\"sub-title\"><span class=\"module-label-in-type\">Module</span>&nbsp;<a href=\"../../../../module-summary.html\">java.compiler</a></div>\n"
				+ "<div class=\"sub-title\"><span class=\"package-label-in-type\">Package</span>&nbsp;<a href=\"package-summary.html\">javax.lang.model.util</a></div>\n"
				+ "<h1 title=\"Class AbstractElementVisitor6\" class=\"title\">Class AbstractElementVisitor6&lt;R,&#8203;P&gt;</h1>\n"
				+ "</div>\n"
				+ "<div class=\"inheritance\" title=\"Inheritance Tree\"><a href=\"../../../../../java.base/java/lang/Object.html\" title=\"class in java.lang\">java.lang.Object</a>\n"
				+ "<div class=\"inheritance\">javax.lang.model.util.AbstractElementVisitor6&lt;R,&#8203;P&gt;</div>\n"
				+ "</div>\n"
				+ "<section class=\"description\">\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Type Parameters:</dt>\n"
				+ "<dd><code>R</code> - the return type of this visitor's methods.  Use <a href=\"../../../../../java.base/java/lang/Void.html\" title=\"class in java.lang\"><code>Void</code></a> for visitors that do not need to return results.</dd>\n"
				+ "<dd><code>P</code> - the type of the additional parameter to this visitor's\n"
				+ "            methods.  Use <code>Void</code> for visitors that do not need an\n"
				+ "            additional parameter.</dd>\n"
				+ "</dl>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>All Implemented Interfaces:</dt>\n"
				+ "<dd><code><a href=\"../element/ElementVisitor.html\" title=\"interface in javax.lang.model.element\">ElementVisitor</a>&lt;R,&#8203;P&gt;</code></dd>\n"
				+ "</dl>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Direct Known Subclasses:</dt>\n"
				+ "<dd><code><a href=\"AbstractElementVisitor7.html\" title=\"class in javax.lang.model.util\">AbstractElementVisitor7</a></code>, <code><a href=\"ElementScanner6.html\" title=\"class in javax.lang.model.util\">ElementScanner6</a></code>, <code><a href=\"SimpleElementVisitor6.html\" title=\"class in javax.lang.model.util\">SimpleElementVisitor6</a></code></dd>\n"
				+ "</dl>\n"
				+ "<hr>\n"
				+ "<pre><a href=\"../../../annotation/processing/SupportedSourceVersion.html\" title=\"annotation in javax.annotation.processing\">@SupportedSourceVersion</a>(<a href=\"../SourceVersion.html#RELEASE_6\">RELEASE_6</a>)\n"
				+ "public abstract class <span class=\"type-name-label\">AbstractElementVisitor6&lt;R,&#8203;P&gt;</span>\n"
				+ "extends <a href=\"../../../../../java.base/java/lang/Object.html\" title=\"class in java.lang\">Object</a>\n"
				+ "implements <a href=\"../element/ElementVisitor.html\" title=\"interface in javax.lang.model.element\">ElementVisitor</a>&lt;R,&#8203;P&gt;</pre>\n"
				+ "<div class=\"block\">A skeletal visitor of program elements with default behavior\n"
				+ " appropriate for the <a href=\"../SourceVersion.html#RELEASE_6\"><code>RELEASE_6</code></a>\n"
				+ " source version.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>API Note:</dt>\n"
				+ "<dd><p id=note_for_subclasses><strong>WARNING:</strong> The <code>\n"
				+ " ElementVisitor</code> interface implemented by this class may have\n"
				+ " methods added to it in the future to accommodate new, currently\n"
				+ " unknown, language structures added to future versions of the\n"
				+ " Java programming language.  Therefore, methods whose names\n"
				+ " begin with <code>\"visit\"</code> may be added to this class in the\n"
				+ " future; to avoid incompatibilities, classes and subclasses which\n"
				+ " extend this class should not declare any instance methods with\n"
				+ " names beginning with <code>\"visit\"</code>.</p>\n"
				+ "\n"
				+ " <p>When such a new visit method is added, the default\n"
				+ " implementation in this class will be to directly or indirectly call\n"
				+ " the <a href=\"#visitUnknown(javax.lang.model.element.Element,P)\"><code>visitUnknown</code></a> method.  A new abstract\n"
				+ " element visitor class will also be introduced to correspond to the\n"
				+ " new language level; this visitor will have different default\n"
				+ " behavior for the visit method in question.  When a new visitor is\n"
				+ " introduced, portions of this visitor class may be deprecated,\n"
				+ " including its constructors.</dd>\n"
				+ "<dt>Since:</dt>\n"
				+ "<dd>1.6</dd>\n"
				+ "<dt>See Also:</dt>\n"
				+ "<dd><a href=\"AbstractElementVisitor7.html\" title=\"class in javax.lang.model.util\"><code>AbstractElementVisitor7</code></a>, \n"
				+ "<a href=\"AbstractElementVisitor8.html\" title=\"class in javax.lang.model.util\"><code>AbstractElementVisitor8</code></a>, \n"
				+ "<a href=\"AbstractElementVisitor9.html\" title=\"class in javax.lang.model.util\"><code>AbstractElementVisitor9</code></a>, \n"
				+ "<a href=\"AbstractElementVisitor14.html\" title=\"class in javax.lang.model.util\"><code>AbstractElementVisitor14</code></a></dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "<section class=\"summary\">\n"
				+ "<ul class=\"summary-list\">\n"
				+ "\n"
				+ "<li>\n"
				+ "<section class=\"constructor-summary\" id=\"constructor.summary\">\n"
				+ "<h2>Constructor Summary</h2>\n"
				+ "<div class=\"member-summary\">\n"
				+ "<table class=\"summary-table\">\n"
				+ "<caption><span>Constructors</span></caption>\n"
				+ "<thead>\n"
				+ "<tr>\n"
				+ "<th class=\"col-first\" scope=\"col\">Modifier</th>\n"
				+ "<th class=\"col-second\" scope=\"col\">Constructor</th>\n"
				+ "<th class=\"col-last\" scope=\"col\">Description</th>\n"
				+ "</tr>\n"
				+ "</thead>\n"
				+ "<tbody>\n"
				+ "<tr class=\"alt-color\">\n"
				+ "<td class=\"col-first\"><code>protected </code></td>\n"
				+ "<th class=\"col-constructor-name\" scope=\"row\"><code><span class=\"member-name-link\"><a href=\"#%3Cinit%3E()\">AbstractElementVisitor6</a></span>()</code></th>\n"
				+ "<td class=\"col-last\">\n"
				+ "<div class=\"block\"><span class=\"deprecated-label\">Deprecated.</span>\n"
				+ "<div class=\"deprecation-comment\">Release 6 is obsolete; update to a visitor for a newer\n"
				+ " release level.</div>\n"
				+ "</div>\n"
				+ "</td>\n"
				+ "</tr>\n"
				+ "</tbody>\n"
				+ "</table>\n"
				+ "</div>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "\n"
				+ "<li>\n"
				+ "<section class=\"method-summary\" id=\"method.summary\">\n"
				+ "<h2>Method Summary</h2>\n"
				+ "<div class=\"member-summary\" id=\"method-summary-table\">\n"
				+ "<div class=\"table-tabs\" role=\"tablist\" aria-orientation=\"horizontal\"><button role=\"tab\" aria-selected=\"true\" aria-controls=\"method-summary-table.tabpanel\" tabindex=\"0\" onkeydown=\"switchTab(event)\" id=\"t0\" class=\"active-table-tab\">All Methods</button><button role=\"tab\" aria-selected=\"false\" aria-controls=\"method-summary-table.tabpanel\" tabindex=\"-1\" onkeydown=\"switchTab(event)\" id=\"t2\" class=\"table-tab\" onclick=\"show(2);\">Instance Methods</button><button role=\"tab\" aria-selected=\"false\" aria-controls=\"method-summary-table.tabpanel\" tabindex=\"-1\" onkeydown=\"switchTab(event)\" id=\"t4\" class=\"table-tab\" onclick=\"show(8);\">Concrete Methods</button></div>\n"
				+ "<div id=\"method-summary-table.tabpanel\" role=\"tabpanel\">\n"
				+ "<table class=\"summary-table\" aria-labelledby=\"t0\">\n"
				+ "<thead>\n"
				+ "<tr>\n"
				+ "<th class=\"col-first\" scope=\"col\">Modifier and Type</th>\n"
				+ "<th class=\"col-second\" scope=\"col\">Method</th>\n"
				+ "<th class=\"col-last\" scope=\"col\">Description</th>\n"
				+ "</tr>\n"
				+ "</thead>\n"
				+ "<tbody>\n"
				+ "<tr class=\"alt-color\" id=\"i0\">\n"
				+ "<td class=\"col-first\"><code><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></code></td>\n"
				+ "<th class=\"col-second\" scope=\"row\"><code><span class=\"member-name-link\"><a href=\"#visit(javax.lang.model.element.Element)\">visit</a></span>&#8203;(<a href=\"../element/Element.html\" title=\"interface in javax.lang.model.element\">Element</a>&nbsp;e)</code></th>\n"
				+ "<td class=\"col-last\">\n"
				+ "<div class=\"block\">Visits any program element as if by passing itself to that\n"
				+ " element's <a href=\"../element/Element.html#accept(javax.lang.model.element.ElementVisitor,P)\"><code>accept</code></a> method and passing\n"
				+ " <code>null</code> for the additional parameter.</div>\n"
				+ "</td>\n"
				+ "</tr>\n"
				+ "<tr class=\"row-color\" id=\"i1\">\n"
				+ "<td class=\"col-first\"><code><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></code></td>\n"
				+ "<th class=\"col-second\" scope=\"row\"><code><span class=\"member-name-link\"><a href=\"#visit(javax.lang.model.element.Element,P)\">visit</a></span>&#8203;(<a href=\"../element/Element.html\" title=\"interface in javax.lang.model.element\">Element</a>&nbsp;e,\n"
				+ "<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&nbsp;p)</code></th>\n"
				+ "<td class=\"col-last\">\n"
				+ "<div class=\"block\">Visits any program element as if by passing itself to that\n"
				+ " element's <a href=\"../element/Element.html#accept(javax.lang.model.element.ElementVisitor,P)\"><code>accept</code></a> method.</div>\n"
				+ "</td>\n"
				+ "</tr>\n"
				+ "<tr class=\"alt-color\" id=\"i2\">\n"
				+ "<td class=\"col-first\"><code><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></code></td>\n"
				+ "<th class=\"col-second\" scope=\"row\"><code><span class=\"member-name-link\"><a href=\"#visitModule(javax.lang.model.element.ModuleElement,P)\">visitModule</a></span>&#8203;(<a href=\"../element/ModuleElement.html\" title=\"interface in javax.lang.model.element\">ModuleElement</a>&nbsp;e,\n"
				+ "<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&nbsp;p)</code></th>\n"
				+ "<td class=\"col-last\">\n"
				+ "<div class=\"block\">Visits a module element.</div>\n"
				+ "</td>\n"
				+ "</tr>\n"
				+ "<tr class=\"row-color\" id=\"i3\">\n"
				+ "<td class=\"col-first\"><code><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></code></td>\n"
				+ "<th class=\"col-second\" scope=\"row\"><code><span class=\"member-name-link\"><a href=\"#visitRecordComponent(javax.lang.model.element.RecordComponentElement,P)\">visitRecordComponent</a></span>&#8203;(<a href=\"../element/RecordComponentElement.html\" title=\"interface in javax.lang.model.element\">RecordComponentElement</a>&nbsp;e,\n"
				+ "<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&nbsp;p)</code></th>\n"
				+ "<td class=\"col-last\">\n"
				+ "<div class=\"block\"><div style=\"display:inline-block; font-weight:bold\">Associated with records, a preview feature of the Java language.</div><br>\n"
				+ "\n"
				+ " Visits a record component element.</div>\n"
				+ "</td>\n"
				+ "</tr>\n"
				+ "<tr class=\"alt-color\" id=\"i4\">\n"
				+ "<td class=\"col-first\"><code><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></code></td>\n"
				+ "<th class=\"col-second\" scope=\"row\"><code><span class=\"member-name-link\"><a href=\"#visitUnknown(javax.lang.model.element.Element,P)\">visitUnknown</a></span>&#8203;(<a href=\"../element/Element.html\" title=\"interface in javax.lang.model.element\">Element</a>&nbsp;e,\n"
				+ "<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&nbsp;p)</code></th>\n"
				+ "<td class=\"col-last\">\n"
				+ "<div class=\"block\">Visits an unknown kind of element.</div>\n"
				+ "</td>\n"
				+ "</tr>\n"
				+ "</tbody>\n"
				+ "</table>\n"
				+ "</div>\n"
				+ "</div>\n"
				+ "<div class=\"inherited-list\">\n"
				+ "<h3 id=\"methods.inherited.from.class.java.lang.Object\">Methods declared in class&nbsp;java.lang.<a href=\"../../../../../java.base/java/lang/Object.html\" title=\"class in java.lang\">Object</a></h3>\n"
				+ "<code><a href=\"../../../../../java.base/java/lang/Object.html#clone()\">clone</a>, <a href=\"../../../../../java.base/java/lang/Object.html#equals(java.lang.Object)\">equals</a>, <a href=\"../../../../../java.base/java/lang/Object.html#finalize()\">finalize</a>, <a href=\"../../../../../java.base/java/lang/Object.html#getClass()\">getClass</a>, <a href=\"../../../../../java.base/java/lang/Object.html#hashCode()\">hashCode</a>, <a href=\"../../../../../java.base/java/lang/Object.html#notify()\">notify</a>, <a href=\"../../../../../java.base/java/lang/Object.html#notifyAll()\">notifyAll</a>, <a href=\"../../../../../java.base/java/lang/Object.html#toString()\">toString</a>, <a href=\"../../../../../java.base/java/lang/Object.html#wait()\">wait</a>, <a href=\"../../../../../java.base/java/lang/Object.html#wait(long)\">wait</a>, <a href=\"../../../../../java.base/java/lang/Object.html#wait(long,int)\">wait</a></code></div>\n"
				+ "<div class=\"inherited-list\">\n"
				+ "<h3 id=\"methods.inherited.from.class.javax.lang.model.element.ElementVisitor\">Methods declared in interface&nbsp;javax.lang.model.element.<a href=\"../element/ElementVisitor.html\" title=\"interface in javax.lang.model.element\">ElementVisitor</a></h3>\n"
				+ "<code><a href=\"../element/ElementVisitor.html#visitExecutable(javax.lang.model.element.ExecutableElement,P)\">visitExecutable</a>, <a href=\"../element/ElementVisitor.html#visitPackage(javax.lang.model.element.PackageElement,P)\">visitPackage</a>, <a href=\"../element/ElementVisitor.html#visitType(javax.lang.model.element.TypeElement,P)\">visitType</a>, <a href=\"../element/ElementVisitor.html#visitTypeParameter(javax.lang.model.element.TypeParameterElement,P)\">visitTypeParameter</a>, <a href=\"../element/ElementVisitor.html#visitVariable(javax.lang.model.element.VariableElement,P)\">visitVariable</a></code></div>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "</ul>\n"
				+ "</section>\n"
				+ "<section class=\"details\">\n"
				+ "<ul class=\"details-list\">\n"
				+ "\n"
				+ "<li>\n"
				+ "<section class=\"constructor-details\" id=\"constructor.detail\">\n"
				+ "<h2>Constructor Details</h2>\n"
				+ "<ul class=\"member-list\">\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"&lt;init&gt;()\">\n"
				+ "<h3>AbstractElementVisitor6</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"annotations\"><a href=\"../../../../../java.base/java/lang/Deprecated.html\" title=\"annotation in java.lang\">@Deprecated</a>(<a href=\"../../../../../java.base/java/lang/Deprecated.html#since()\">since</a>=\"9\")\n"
				+ "</span><span class=\"modifiers\">protected</span>&nbsp;<span class=\"member-name\">AbstractElementVisitor6</span>()</div>\n"
				+ "<div class=\"deprecation-block\"><span class=\"deprecated-label\">Deprecated.</span>\n"
				+ "<div class=\"deprecation-comment\">Release 6 is obsolete; update to a visitor for a newer\n"
				+ " release level.</div>\n"
				+ "</div>\n"
				+ "<div class=\"block\">Constructor for concrete subclasses to call.</div>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "</ul>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "\n"
				+ "<li>\n"
				+ "<section class=\"method-details\" id=\"method.detail\">\n"
				+ "<h2>Method Details</h2>\n"
				+ "<ul class=\"member-list\">\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"visit(javax.lang.model.element.Element,P)\">\n"
				+ "<h3 id=\"visit(javax.lang.model.element.Element,java.lang.Object)\">visit</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public final</span>&nbsp;<span class=\"return-type\"><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></span>&nbsp;<span class=\"member-name\">visit</span>&#8203;(<span class=\"parameters\"><a href=\"../element/Element.html\" title=\"interface in javax.lang.model.element\">Element</a>&nbsp;e,\n"
				+ "<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&nbsp;p)</span></div>\n"
				+ "<div class=\"block\">Visits any program element as if by passing itself to that\n"
				+ " element's <a href=\"../element/Element.html#accept(javax.lang.model.element.ElementVisitor,P)\"><code>accept</code></a> method.  The invocation\n"
				+ " <code>v.visit(elem, p)</code> is equivalent to <code>elem.accept(v,\n"
				+ " p)</code>.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Specified by:</dt>\n"
				+ "<dd><code><a href=\"../element/ElementVisitor.html#visit(javax.lang.model.element.Element,P)\">visit</a></code>&nbsp;in interface&nbsp;<code><a href=\"../element/ElementVisitor.html\" title=\"interface in javax.lang.model.element\">ElementVisitor</a>&lt;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a>,&#8203;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&gt;</code></dd>\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>e</code> - the element to visit</dd>\n"
				+ "<dd><code>p</code> - a visitor-specified parameter</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>a visitor-specified result</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"visit(javax.lang.model.element.Element)\">\n"
				+ "<h3>visit</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public final</span>&nbsp;<span class=\"return-type\"><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></span>&nbsp;<span class=\"member-name\">visit</span>&#8203;(<span class=\"parameters\"><a href=\"../element/Element.html\" title=\"interface in javax.lang.model.element\">Element</a>&nbsp;e)</span></div>\n"
				+ "<div class=\"block\">Visits any program element as if by passing itself to that\n"
				+ " element's <a href=\"../element/Element.html#accept(javax.lang.model.element.ElementVisitor,P)\"><code>accept</code></a> method and passing\n"
				+ " <code>null</code> for the additional parameter.  The invocation\n"
				+ " <code>v.visit(elem)</code> is equivalent to <code>elem.accept(v,\n"
				+ " null)</code>.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Specified by:</dt>\n"
				+ "<dd><code><a href=\"../element/ElementVisitor.html#visit(javax.lang.model.element.Element)\">visit</a></code>&nbsp;in interface&nbsp;<code><a href=\"../element/ElementVisitor.html\" title=\"interface in javax.lang.model.element\">ElementVisitor</a>&lt;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a>,&#8203;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&gt;</code></dd>\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>e</code> - the element to visit</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>a visitor-specified result</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"visitUnknown(javax.lang.model.element.Element,P)\">\n"
				+ "<h3 id=\"visitUnknown(javax.lang.model.element.Element,java.lang.Object)\">visitUnknown</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public</span>&nbsp;<span class=\"return-type\"><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></span>&nbsp;<span class=\"member-name\">visitUnknown</span>&#8203;(<span class=\"parameters\"><a href=\"../element/Element.html\" title=\"interface in javax.lang.model.element\">Element</a>&nbsp;e,\n"
				+ "<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&nbsp;p)</span></div>\n"
				+ "<div class=\"block\">Visits an unknown kind of element.\n"
				+ " This can occur if the language evolves and new kinds\n"
				+ " of elements are added to the <code>Element</code> hierarchy.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Specified by:</dt>\n"
				+ "<dd><code><a href=\"../element/ElementVisitor.html#visitUnknown(javax.lang.model.element.Element,P)\">visitUnknown</a></code>&nbsp;in interface&nbsp;<code><a href=\"../element/ElementVisitor.html\" title=\"interface in javax.lang.model.element\">ElementVisitor</a>&lt;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a>,&#8203;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&gt;</code></dd>\n"
				+ "<dt>Implementation Requirements:</dt>\n"
				+ "<dd>The default implementation of this method in\n"
				+ " <code>AbstractElementVisitor6</code> will always throw\n"
				+ " <code>new UnknownElementException(e, p)</code>.\n"
				+ " This behavior is not required of a subclass.</dd>\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>e</code> - the element to visit</dd>\n"
				+ "<dd><code>p</code> - a visitor-specified parameter</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>a visitor-specified result</dd>\n"
				+ "<dt>Throws:</dt>\n"
				+ "<dd><code><a href=\"../element/UnknownElementException.html\" title=\"class in javax.lang.model.element\">UnknownElementException</a></code> - a visitor implementation may optionally throw this exception</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"visitModule(javax.lang.model.element.ModuleElement,P)\">\n"
				+ "<h3 id=\"visitModule(javax.lang.model.element.ModuleElement,java.lang.Object)\">visitModule</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public</span>&nbsp;<span class=\"return-type\"><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></span>&nbsp;<span class=\"member-name\">visitModule</span>&#8203;(<span class=\"parameters\"><a href=\"../element/ModuleElement.html\" title=\"interface in javax.lang.model.element\">ModuleElement</a>&nbsp;e,\n"
				+ "<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&nbsp;p)</span></div>\n"
				+ "<div class=\"block\">Visits a module element.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Specified by:</dt>\n"
				+ "<dd><code><a href=\"../element/ElementVisitor.html#visitModule(javax.lang.model.element.ModuleElement,P)\">visitModule</a></code>&nbsp;in interface&nbsp;<code><a href=\"../element/ElementVisitor.html\" title=\"interface in javax.lang.model.element\">ElementVisitor</a>&lt;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a>,&#8203;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&gt;</code></dd>\n"
				+ "<dt>Implementation Requirements:</dt>\n"
				+ "<dd>Visits a <code>ModuleElement</code> by calling <code>\n"
				+ " visitUnknown</code>.</dd>\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>e</code> - the element to visit</dd>\n"
				+ "<dd><code>p</code> - a visitor-specified parameter</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>a visitor-specified result</dd>\n"
				+ "<dt>Since:</dt>\n"
				+ "<dd>9</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"visitRecordComponent(javax.lang.model.element.RecordComponentElement,P)\">\n"
				+ "<h3 id=\"visitRecordComponent(javax.lang.model.element.RecordComponentElement,java.lang.Object)\">visitRecordComponent</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public</span>&nbsp;<span class=\"return-type\"><a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a></span>&nbsp;<span class=\"member-name\">visitRecordComponent</span>&#8203;(<span class=\"parameters\"><a href=\"../element/RecordComponentElement.html\" title=\"interface in javax.lang.model.element\">RecordComponentElement</a>&nbsp;e,\n"
				+ "<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&nbsp;p)</span></div>\n"
				+ "<div class=\"block\"><div style=\"border: 1px solid red; border-radius: 5px; padding: 5px; display:inline-block; font-size: larger\">           This method is associated with <i>records</i>, a preview\n"
				+ "           feature of the Java language. Preview features\n"
				+ "           may be removed in a future release, or upgraded to permanent\n"
				+ "           features of the Java language.</div><br>\n"
				+ "\n"
				+ " Visits a record component element.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Specified by:</dt>\n"
				+ "<dd><code><a href=\"../element/ElementVisitor.html#visitRecordComponent(javax.lang.model.element.RecordComponentElement,P)\">visitRecordComponent</a></code>&nbsp;in interface&nbsp;<code><a href=\"../element/ElementVisitor.html\" title=\"interface in javax.lang.model.element\">ElementVisitor</a>&lt;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">R</a>,&#8203;<a href=\"AbstractElementVisitor6.html\" title=\"type parameter in AbstractElementVisitor6\">P</a>&gt;</code></dd>\n"
				+ "<dt>Implementation Requirements:</dt>\n"
				+ "<dd>Visits a <code>RecordComponentElement</code> by calling <code>\n"
				+ " visitUnknown</code>.</dd>\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>e</code> - the element to visit</dd>\n"
				+ "<dd><code>p</code> - a visitor-specified parameter</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>a visitor-specified result</dd>\n"
				+ "<dt>Since:</dt>\n"
				+ "<dd>14</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "</ul>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "</ul>\n"
				+ "</section>\n"
				+ "\n"
				+ "</main>\n"
				+ "<footer role=\"contentinfo\">\n"
				+ "<nav role=\"navigation\">\n"
				+ "\n"
				+ "<div class=\"bottom-nav\" id=\"navbar.bottom\">\n"
				+ "<div class=\"skip-nav\"><a href=\"#skip.navbar.bottom\" title=\"Skip navigation links\">Skip navigation links</a></div>\n"
				+ "<ul id=\"navbar.bottom.firstrow\" class=\"nav-list\" title=\"Navigation\">\n"
				+ "<li><a href=\"../../../../../index.html\">Overview</a></li>\n"
				+ "<li><a href=\"../../../../module-summary.html\">Module</a></li>\n"
				+ "<li><a href=\"package-summary.html\">Package</a></li>\n"
				+ "<li class=\"nav-bar-cell1-rev\">Class</li>\n"
				+ "<li><a href=\"class-use/AbstractElementVisitor6.html\">Use</a></li>\n"
				+ "<li><a href=\"package-tree.html\">Tree</a></li>\n"
				+ "<li><a href=\"../../../../../deprecated-list.html\">Deprecated</a></li>\n"
				+ "<li><a href=\"../../../../../index-files/index-1.html\">Index</a></li>\n"
				+ "<li><a href=\"../../../../../help-doc.html\">Help</a></li>\n"
				+ "</ul>\n"
				+ "<div class=\"about-language\"><div style=\"margin-top: 14px;\"><strong>Java SE 15 &amp; JDK 15</strong> </div></div>\n"
				+ "</div>\n"
				+ "<div class=\"sub-nav\">\n"
				+ "<div>\n"
				+ "<ul class=\"sub-nav-list\">\n"
				+ "<li>Summary:&nbsp;</li>\n"
				+ "<li>Nested&nbsp;|&nbsp;</li>\n"
				+ "<li>Field&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#constructor.summary\">Constr</a>&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#method.summary\">Method</a></li>\n"
				+ "</ul>\n"
				+ "<ul class=\"sub-nav-list\">\n"
				+ "<li>Detail:&nbsp;</li>\n"
				+ "<li>Field&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#constructor.detail\">Constr</a>&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#method.detail\">Method</a></li>\n"
				+ "</ul>\n"
				+ "</div>\n"
				+ "</div>\n"
				+ "\n"
				+ "<span class=\"skip-nav\" id=\"skip.navbar.bottom\">\n"
				+ "\n"
				+ "</span></nav>\n"
				+ "<p class=\"legal-copy\"><small><a href=\"https://bugreport.java.com/bugreport/\">Report a bug or suggest an enhancement</a><br> For further API reference and developer documentation see the <a href=\"https://docs.oracle.com/pls/topic/lookup?ctx=javase15.0.2&amp;id=homepage\" target=\"_blank\">Java SE Documentation</a>, which contains more detailed, developer-targeted descriptions with conceptual overviews, definitions of terms, workarounds, and working code examples.<br> Java is a trademark or registered trademark of Oracle and/or its affiliates in the US and other countries.<br> <a href=\"../../../../../../legal/copyright.html\">Copyright</a> &copy; 1993, 2020, Oracle and/or its affiliates, 500 Oracle Parkway, Redwood Shores, CA 94065 USA.<br>All rights reserved. Use is subject to <a href=\"https://www.oracle.com/technetwork/java/javase/terms/license/java15.0.2speclicense.html\">license terms</a> and the <a href=\"https://www.oracle.com/technetwork/java/redist-137594.html\">documentation redistribution policy</a>. </small></p>\n"
				+ "</footer>\n"
				+ "</div>\n"
				+ "</div>\n"
				+ "</body>\n"
				+ "</html>n class=\"return-type\"><a href=\"SourceVersion.html\" title=\"enum in javax.lang.model\">SourceVersion</a>[]</span>&nbsp;<span class=\"member-name\">values</span>()</div>\n"
				+ "<div class=\"block\">Returns an array containing the constants of this enum type, in\n"
				+ "the order they are declared.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>an array containing the constants of this enum type, in the order they are declared</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"valueOf(java.lang.String)\">\n"
				+ "<h3>valueOf</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public static</span>&nbsp;<span class=\"return-type\"><a href=\"SourceVersion.html\" title=\"enum in javax.lang.model\">SourceVersion</a></span>&nbsp;<span class=\"member-name\">valueOf</span>&#8203;(<span class=\"parameters\"><a href=\"../../../../java.base/java/lang/String.html\" title=\"class in java.lang\">String</a>&nbsp;name)</span></div>\n"
				+ "<div class=\"block\">Returns the enum constant of this type with the specified name.\n"
				+ "The string must match <i>exactly</i> an identifier used to declare an\n"
				+ "enum constant in this type.  (Extraneous whitespace characters are \n"
				+ "not permitted.)</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>name</code> - the name of the enum constant to be returned.</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>the enum constant with the specified name</dd>\n"
				+ "<dt>Throws:</dt>\n"
				+ "<dd><code><a href=\"../../../../java.base/java/lang/IllegalArgumentException.html\" title=\"class in java.lang\">IllegalArgumentException</a></code> - if this enum type has no constant with the specified name</dd>\n"
				+ "<dd><code><a href=\"../../../../java.base/java/lang/NullPointerException.html\" title=\"class in java.lang\">NullPointerException</a></code> - if the argument is null</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"latest()\">\n"
				+ "<h3>latest</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public static</span>&nbsp;<span class=\"return-type\"><a href=\"SourceVersion.html\" title=\"enum in javax.lang.model\">SourceVersion</a></span>&nbsp;<span class=\"member-name\">latest</span>()</div>\n"
				+ "<div class=\"block\">Returns the latest source version that can be modeled.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>the latest source version that can be modeled</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"latestSupported()\">\n"
				+ "<h3>latestSupported</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public static</span>&nbsp;<span class=\"return-type\"><a href=\"SourceVersion.html\" title=\"enum in javax.lang.model\">SourceVersion</a></span>&nbsp;<span class=\"member-name\">latestSupported</span>()</div>\n"
				+ "<div class=\"block\">Returns the latest source version fully supported by the\n"
				+ " current execution environment.  <code>RELEASE_9</code> or later must\n"
				+ " be returned.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>API Note:</dt>\n"
				+ "<dd>This method is included alongside <a href=\"#latest()\"><code>latest()</code></a> to\n"
				+ " allow identification of situations where the language model API\n"
				+ " is running on a platform version different than the latest\n"
				+ " version modeled by the API. One way that sort of situation can\n"
				+ " occur is if an IDE or similar tool is using the API to model\n"
				+ " source version <i>N</i> while running on platform version\n"
				+ " (<i>N</i>&nbsp;-&nbsp;1). Running in this configuration is\n"
				+ " supported by the API. Running an API on platform versions\n"
				+ " earlier than (<i>N</i>&nbsp;-&nbsp;1) or later than <i>N</i>\n"
				+ " may or may not work as an implementation detail. If an\n"
				+ " annotation processor was generating code to run under the\n"
				+ " current execution environment, the processor should only use\n"
				+ " platform features up to the <code>latestSupported</code> release,\n"
				+ " which may be earlier than the <code>latest</code> release.</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd>the latest source version that is fully supported</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"isIdentifier(java.lang.CharSequence)\">\n"
				+ "<h3>isIdentifier</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public static</span>&nbsp;<span class=\"return-type\">boolean</span>&nbsp;<span class=\"member-name\">isIdentifier</span>&#8203;(<span class=\"parameters\"><a href=\"../../../../java.base/java/lang/CharSequence.html\" title=\"interface in java.lang\">CharSequence</a>&nbsp;name)</span></div>\n"
				+ "<div class=\"block\">Returns whether or not <code>name</code> is a syntactically valid\n"
				+ " identifier (simple name) or keyword in the latest source\n"
				+ " version.  The method returns <code>true</code> if the name consists\n"
				+ " of an initial character for which <a href=\"../../../../java.base/java/lang/Character.html#isJavaIdentifierStart(int)\"><code>Character.isJavaIdentifierStart(int)</code></a> returns <code>true</code>,\n"
				+ " followed only by characters for which <a href=\"../../../../java.base/java/lang/Character.html#isJavaIdentifierPart(int)\"><code>Character.isJavaIdentifierPart(int)</code></a> returns <code>true</code>.\n"
				+ " This pattern matches regular identifiers, keywords, restricted\n"
				+ " keywords, restricted identifiers and the literals <code>\"true\"</code>,\n"
				+ " <code>\"false\"</code>, <code>\"null\"</code>.\n"
				+ "\n"
				+ " The method returns <code>false</code> for all other strings.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>name</code> - the string to check</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd><code>true</code> if this string is a\n"
				+ " syntactically valid identifier or keyword, <code>false</code>\n"
				+ " otherwise.</dd>\n"
				+ "<dt>See <i>Java Language Specification</i>:</dt>\n"
				+ "<dd>\n"
				+ "<a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.8\">3.8 Identifiers</a><br></dd></dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"isName(java.lang.CharSequence)\">\n"
				+ "<h3>isName</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public static</span>&nbsp;<span class=\"return-type\">boolean</span>&nbsp;<span class=\"member-name\">isName</span>&#8203;(<span class=\"parameters\"><a href=\"../../../../java.base/java/lang/CharSequence.html\" title=\"interface in java.lang\">CharSequence</a>&nbsp;name)</span></div>\n"
				+ "<div class=\"block\">Returns whether or not <code>name</code> is a syntactically valid\n"
				+ " qualified name in the latest source version.\n"
				+ "\n"
				+ " Syntactically, a qualified name is a sequence of identifiers\n"
				+ " separated by period characters (\"<code>.</code>\"). This method\n"
				+ " splits the input string into period-separated segments and\n"
				+ " applies checks to each segment in turn.\n"
				+ "\n"
				+ " Unlike <a href=\"#isIdentifier(java.lang.CharSequence)\"><code>isIdentifier</code></a>, this method returns\n"
				+ " <code>false</code> for keywords, boolean literals, and the null\n"
				+ " literal in any segment.\n"
				+ "\n"
				+ " This method returns <code>true</code> for <i>restricted\n"
				+ " keywords</i> and <i>restricted identifiers</i>.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>name</code> - the string to check</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd><code>true</code> if this string is a\n"
				+ " syntactically valid name, <code>false</code> otherwise.</dd>\n"
				+ "<dt>See <i>Java Language Specification</i>:</dt>\n"
				+ "<dd>\n"
				+ "<a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.9\">3.9 Keywords</a><br><a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-6.html#jls-6.2\">6.2 Names and Identifiers</a><br></dd></dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"isName(java.lang.CharSequence,javax.lang.model.SourceVersion)\">\n"
				+ "<h3>isName</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public static</span>&nbsp;<span class=\"return-type\">boolean</span>&nbsp;<span class=\"member-name\">isName</span>&#8203;(<span class=\"parameters\"><a href=\"../../../../java.base/java/lang/CharSequence.html\" title=\"interface in java.lang\">CharSequence</a>&nbsp;name,\n"
				+ "<a href=\"SourceVersion.html\" title=\"enum in javax.lang.model\">SourceVersion</a>&nbsp;version)</span></div>\n"
				+ "<div class=\"block\">Returns whether or not <code>name</code> is a syntactically valid\n"
				+ " qualified name in the given source version.\n"
				+ "\n"
				+ " Syntactically, a qualified name is a sequence of identifiers\n"
				+ " separated by period characters (\"<code>.</code>\"). This method\n"
				+ " splits the input string into period-separated segments and\n"
				+ " applies checks to each segment in turn.\n"
				+ "\n"
				+ " Unlike <a href=\"#isIdentifier(java.lang.CharSequence)\"><code>isIdentifier</code></a>, this method returns\n"
				+ " <code>false</code> for keywords, boolean literals, and the null\n"
				+ " literal in any segment.\n"
				+ "\n"
				+ " This method returns <code>true</code> for <i>restricted\n"
				+ " keywords</i> and <i>restricted identifiers</i>.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>name</code> - the string to check</dd>\n"
				+ "<dd><code>version</code> - the version to use</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd><code>true</code> if this string is a\n"
				+ " syntactically valid name, <code>false</code> otherwise.</dd>\n"
				+ "<dt>See <i>Java Language Specification</i>:</dt>\n"
				+ "<dd>\n"
				+ "<a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.9\">3.9 Keywords</a><br><a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-6.html#jls-6.2\">6.2 Names and Identifiers</a><br></dd>\n"
				+ "<dt>Since:</dt>\n"
				+ "<dd>9</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"isKeyword(java.lang.CharSequence)\">\n"
				+ "<h3>isKeyword</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public static</span>&nbsp;<span class=\"return-type\">boolean</span>&nbsp;<span class=\"member-name\">isKeyword</span>&#8203;(<span class=\"parameters\"><a href=\"../../../../java.base/java/lang/CharSequence.html\" title=\"interface in java.lang\">CharSequence</a>&nbsp;s)</span></div>\n"
				+ "<div class=\"block\">Returns whether or not <code>s</code> is a keyword, boolean literal,\n"
				+ " or null literal in the latest source version.\n"
				+ " This method returns <code>false</code> for <i>restricted\n"
				+ " keywords</i> and <i>restricted identifiers</i>.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>s</code> - the string to check</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd><code>true</code> if <code>s</code> is a keyword, or boolean\n"
				+ " literal, or null literal, <code>false</code> otherwise.</dd>\n"
				+ "<dt>See <i>Java Language Specification</i>:</dt>\n"
				+ "<dd>\n"
				+ "<a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.9\">3.9 Keywords</a><br><a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.10.3\">3.10.3 Boolean Literals</a><br><a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.10.7\">3.10.7 The Null Literal</a><br></dd></dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "<li>\n"
				+ "<section class=\"detail\" id=\"isKeyword(java.lang.CharSequence,javax.lang.model.SourceVersion)\">\n"
				+ "<h3>isKeyword</h3>\n"
				+ "<div class=\"member-signature\"><span class=\"modifiers\">public static</span>&nbsp;<span class=\"return-type\">boolean</span>&nbsp;<span class=\"member-name\">isKeyword</span>&#8203;(<span class=\"parameters\"><a href=\"../../../../java.base/java/lang/CharSequence.html\" title=\"interface in java.lang\">CharSequence</a>&nbsp;s,\n"
				+ "<a href=\"SourceVersion.html\" title=\"enum in javax.lang.model\">SourceVersion</a>&nbsp;version)</span></div>\n"
				+ "<div class=\"block\">Returns whether or not <code>s</code> is a keyword, boolean literal,\n"
				+ " or null literal in the given source version.\n"
				+ " This method returns <code>false</code> for <i>restricted\n"
				+ " keywords</i> and <i>restricted identifiers</i>.</div>\n"
				+ "<dl class=\"notes\">\n"
				+ "<dt>Parameters:</dt>\n"
				+ "<dd><code>s</code> - the string to check</dd>\n"
				+ "<dd><code>version</code> - the version to use</dd>\n"
				+ "<dt>Returns:</dt>\n"
				+ "<dd><code>true</code> if <code>s</code> is a keyword, or boolean\n"
				+ " literal, or null literal, <code>false</code> otherwise.</dd>\n"
				+ "<dt>See <i>Java Language Specification</i>:</dt>\n"
				+ "<dd>\n"
				+ "<a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.9\">3.9 Keywords</a><br><a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.10.3\">3.10.3 Boolean Literals</a><br><a href=\"https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.10.7\">3.10.7 The Null Literal</a><br></dd>\n"
				+ "<dt>Since:</dt>\n"
				+ "<dd>9</dd>\n"
				+ "</dl>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "</ul>\n"
				+ "</section>\n"
				+ "</li>\n"
				+ "</ul>\n"
				+ "</section>\n"
				+ "\n"
				+ "</main>\n"
				+ "<footer role=\"contentinfo\">\n"
				+ "<nav role=\"navigation\">\n"
				+ "\n"
				+ "<div class=\"bottom-nav\" id=\"navbar.bottom\">\n"
				+ "<div class=\"skip-nav\"><a href=\"#skip.navbar.bottom\" title=\"Skip navigation links\">Skip navigation links</a></div>\n"
				+ "<ul id=\"navbar.bottom.firstrow\" class=\"nav-list\" title=\"Navigation\">\n"
				+ "<li><a href=\"../../../../index.html\">Overview</a></li>\n"
				+ "<li><a href=\"../../../module-summary.html\">Module</a></li>\n"
				+ "<li><a href=\"package-summary.html\">Package</a></li>\n"
				+ "<li class=\"nav-bar-cell1-rev\">Class</li>\n"
				+ "<li><a href=\"class-use/SourceVersion.html\">Use</a></li>\n"
				+ "<li><a href=\"package-tree.html\">Tree</a></li>\n"
				+ "<li><a href=\"../../../../deprecated-list.html\">Deprecated</a></li>\n"
				+ "<li><a href=\"../../../../index-files/index-1.html\">Index</a></li>\n"
				+ "<li><a href=\"../../../../help-doc.html\">Help</a></li>\n"
				+ "</ul>\n"
				+ "<div class=\"about-language\"><div style=\"margin-top: 14px;\"><strong>Java SE 15 &amp; JDK 15</strong> </div></div>\n"
				+ "</div>\n"
				+ "<div class=\"sub-nav\">\n"
				+ "<div>\n"
				+ "<ul class=\"sub-nav-list\">\n"
				+ "<li>Summary:&nbsp;</li>\n"
				+ "<li><a href=\"#nested.class.summary\">Nested</a>&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#enum.constant.summary\">Enum Constants</a>&nbsp;|&nbsp;</li>\n"
				+ "<li>Field&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#method.summary\">Method</a></li>\n"
				+ "</ul>\n"
				+ "<ul class=\"sub-nav-list\">\n"
				+ "<li>Detail:&nbsp;</li>\n"
				+ "<li><a href=\"#enum.constant.detail\">Enum Constants</a>&nbsp;|&nbsp;</li>\n"
				+ "<li>Field&nbsp;|&nbsp;</li>\n"
				+ "<li><a href=\"#method.detail\">Method</a></li>\n"
				+ "</ul>\n"
				+ "</div>\n"
				+ "</div>\n"
				+ "\n"
				+ "<span class=\"skip-nav\" id=\"skip.navbar.bottom\">\n"
				+ "\n"
				+ "</span></nav>\n"
				+ "<p class=\"legal-copy\"><small><a href=\"https://bugreport.java.com/bugreport/\">Report a bug or suggest an enhancement</a><br> For further API reference and developer documentation see the <a href=\"https://docs.oracle.com/pls/topic/lookup?ctx=javase15.0.2&amp;id=homepage\" target=\"_blank\">Java SE Documentation</a>, which contains more detailed, developer-targeted descriptions with conceptual overviews, definitions of terms, workarounds, and working code examples.<br> Java is a trademark or registered trademark of Oracle and/or its affiliates in the US and other countries.<br> <a href=\"../../../../../legal/copyright.html\">Copyright</a> &copy; 1993, 2020, Oracle and/or its affiliates, 500 Oracle Parkway, Redwood Shores, CA 94065 USA.<br>All rights reserved. Use is subject to <a href=\"https://www.oracle.com/technetwork/java/javase/terms/license/java15.0.2speclicense.html\">license terms</a> and the <a href=\"https://www.oracle.com/technetwork/java/redist-137594.html\">documentation redistribution policy</a>. </small></p>\n"
				+ "</footer>\n"
				+ "</div>\n"
				+ "</div>\n"
				+ "</body>\n"
				+ "</html>");
		
		System.out.println(validLinks);
		
		
		// this throws an exception
		URL invalid = new URL("javascript:alert('Hello!');");
		System.out.println(invalid);
		
		
		
	}
}
